### ISSUE TITLE
rust-crypto dependency prevents compiling to wasm

### ISSUE THREAD

**Issue by Schaeff** [matter-labs/sapling-crypto#11]
`rust-crypto` doesn't compile to wasm due to the outdated `rustc-serialize` dependency.

There are fixes at different levels:
- [at the `rustc-serialize` level](https://crates.io/crates/rustc-serialize2)
- [at the `rust-crypto` level](https://crates.io/crates/rust-crypto-wasm)

Our quick fix is [here](https://github.com/matter-labs/sapling-crypto/compare/master...dark64:master) but we want to avoid forking this repo.

What approach would you prefer?

**Comment by shamatar** [comment]
I think that `rust-crypto` is only used for SHA256, so may be it's worth to replace it all together with something more lightweight like [this](https://github.com/RustCrypto/hashes)? Otherwise I'd switch to `rust-crypto-wasm` for now, but it still takes all the libc together with it.

**Comment by dark64** [comment]
> I think that `rust-crypto` is only used for SHA256, so may be it's worth to replace it all together with something more lightweight like [this](https://github.com/RustCrypto/hashes)? Otherwise I'd switch to `rust-crypto-wasm` for now, but it still takes all the libc together with it.

I made a pull request regarding this issue [https://github.com/matter-labs/sapling-crypto/pull/12](https://github.com/matter-labs/sapling-crypto/pull/12) @shamatar

**Comment by shamatar** [comment]
Thank you @dark64 ! @Schaeff would you try to check PR #12 against you WASM target?

**Comment by Schaeff** [comment]
Hey @shamatar yes everything works fine for us with this change!

**Comment by shamatar** [comment]
Version 0.1.1 should be now on crates.io. If it's good then please close this issue

**Comment by Schaeff** [comment]
Very good thanks!
